# Generated by Django 3.2.11 on 2022-01-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_oferta_zdjecie_glowne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('zdjecie_glowne', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
