# Generated by Django 3.2.11 on 2022-01-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ksiazki_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazki',
            name='link',
            field=models.CharField(default='link', max_length=100),
            preserve_default=False,
        ),
    ]
