# Generated by Django 3.1.5 on 2022-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ksiazki_opis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksiazki',
            options={'verbose_name': 'Ksiażka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='name',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='opis',
        ),
        migrations.AddField(
            model_name='oferta',
            name='cena',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='cena_nie_zawiera',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='cena_zawiera',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='historia',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='opis_dni',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='termin',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tytul',
            field=models.TextField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='uwagi',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wazne_informacje',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
