# Generated by Django 3.2.11 on 2022-02-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220213_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zdjecia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.oferta')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
            },
        ),
    ]
